version: '3.8'
services:
  api:
    build: .
    ports:
      - "5000:80"
      - "5001:443"
    env_file: 
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ConnectionStrings__DefaultConnection=Server=db;Database=${DATABASE_NAME};User=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    depends_on:
      - db
    
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file: 
      - .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - emailalias-db:/var/opt/mssql

volumes:
  emailalias-db: 